# Generated by Django 3.2.9 on 2021-12-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=96)),
                ('stock_ticker', models.CharField(max_length=5)),
                ('event_date', models.CharField(max_length=15)),
                ('catalyst_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock_app.user')),
            ],
        ),
    ]
